### ISSUE TITLE
First age techs - too expensive?

### ISSUE THREAD

**Issue by gdarai** [gdarai/SpaceRace#15]
Hi guys

I am thinking about some improvements which are almost too expensive:

Hoppers -> I think Alu plate and Tin plate hoppers are nonsence (doubles the cost in metal). Maybe low grade metal ingots hoppers instead? Like copper, Tin, Bronze, Brass, Nickel, Zinc... all of it.

Crusher -> Isn't it just too expensive? I don't know. Would it help to make steel fences 2x cheaper?

Protein liquifier -> I have to check if I can make the process RF less expensive.

Ammo for revolver -> Needs Gunpowder... Big time. I have to think about some good source for that. Any suggestions? The re is some unused Ore for Sulfur, maybe I can use that. But I would like multiple ways.

Also found a bug:
Bayonett -> Requires Iron Sword which does not have recipe... hmm, I need to fix that.

**Comment by OlorinCZ** [comment]
Well, I'm not quite there (but almost) so for my five gold nuggets:

Hoppers - I actually made some of these when I was low on iron and swimming in Alu, so under some conditions... having greater variability would certainly help to some degree.

Crusher - I was pleased to see I could build it before venturing into the under end - and then I found out it was not manageable without some better infrastructure. I have recently finished boosting it so maybe I will redo the calculations. It certainly seemed before like it would swallow a lot of steel, dunno now.

Ammo - Agreed; the gunpowder cost is a major turndown for the otherwise awesome looking revolver. It made me stick to the old trusty TiCon crossbow, which has self-refilling ammo and kicks like a horse. Wonder how they would compare damage-wise btw. As for the gunpowder, how about crusher recipe from netherrack? It sure seems hellish enough.

**Comment by OlorinCZ** [comment]
Ok, after doing the calculations on the steel costs of a Crusher I concluded that surprisingly large part of that cost comes from making the steel rods, as on the tech level where you want to build the crusher it costs you 3 ingots per rod and you need 19 of them. That is so much I am seriously considering skipping crusher until I can build that goddamned IE rolling machine which makes them for 1 ingot each. The difference is just too steep.
Sugestions: Out of all the differnet blocks, steel fences definetly seem overpriced. Doubling the amount you get from that recipe would seem right. Or, as a more extreme (albeit welcome) measure, just lower the material cost of all tough rods to two ingots per piece...

**Comment by gdarai** [comment]
Yes I noticed that too... the thing with crushed obsidian is an overlook... I have to fix it now. so I added 2 other ways how to make the crushed obsidian without crusher. I will release this ASAP.

As for the price of the rod... I am hesitating to decrease the price globally like that... that would have huge impact... I will improve the fence prices though. That should be enough for now.
