### ISSUE TITLE
Skipping Crusher

### ISSUE THREAD

**Issue by gdarai** [gdarai/SpaceRace#16]
One of big topics was if it is necessary to build a crusher...
I wanted it to be possible at least before space. As i looks it is not the case. We fixed the Obsidian Dust isssue... but now there is a new issue: the proxii dust.

Well, that brings a question: Should I skipp dusts in recipes all together, or should I add a way to make them? I am thinking about making dust fom ingot using flint and hammer... or using small plate press... or adding nugget variant of the recipes. The proxii stuff is to expensive anyway I think.
One proxii dust = ingot... that is a lot for one transistor, isn't it?

**Comment by gdarai** [comment]
So... i checked it and current setting gives the player way to make dust with hammer for everything we have ore for. But not for alloys. So, I see two ways... allow smashing alloyed ingots or allow mixing dusts...

Maybe I can give the user both ways. Smashing ingots would cost flint, mixing dusts would be loosing the 1.5 production multiplier of smeltery.

And I will increase the Crystalizer output aprox. 3x

**Comment by OlorinCZ** [comment]
Again, I have not made much progress into the field of advanced electronics as it's all new stuff for me, but as I was looking for the alternative recipies for circiuts, the transistors indeed seemed quite expensive; mainly because of the proxii dust.

Having multiple ways seems good; that way each player can do what fits him most. And with mixing dust there is another reward for building the crusher: You can keep the 2x multiplication bonus while skipping the tedious part where you crush the ores, smelt them, alloy them and cast them only to have them crushed again. I like it.
