### ISSUE TITLE
Mettalic bees - no easy go

### ISSUE THREAD

**Issue by gdarai** [gdarai/SpaceRace#19]
It looks like that for first mutation of bees the correct biome is needed.
In this case, the metallic bees needs hellish biome to start live.
https://forum.feed-the-beast.com/threads/hellish-alveary.21018/

My only idea I have now is to add the nether biome to some island, or parts of the underend.
And of course find another condtion for tier 3 plants than metallic propolis.

**Comment by kotja3** [comment]
What about gendustry mutator?

**Comment by OlorinCZ** [comment]
Since the underend has those giant lava lakes, netherrack and lava slimes, having a (partialy) hellish biome would seem appropriate. Solutions like gendustry are viable, but very late game in this pack.

As for the suggestions for making tier 3 plants, I would go for either plain propolis (you need at least diligent/industrious bee branch for it) which currently has only a few uses and is decently common. Or if you want something rarer use the crystal propolis, which requires you finding some steadfast drones in a chest somewhere and succesfully breeding them with hardened bees to make redstone and other crystal producing bees.

**Comment by kotja3** [comment]
You can get propolis from tropical bees from jungle and if you plan to upgrade your forestry packs you will end with some.

**Comment by gdarai** [comment]
Mutator is available, but as middle age tech, definitley not on the overworld.. I think I made it available since the first Asteroid belt.

Right now, I am thinking about how to do it, that we actually can breed bees which need hellish outside hell... and from what Forestry guys said, it is enough to set type of biome to NETHER.. well, I am trying, not working yet, hopefully guys from BiomeTweaker will tell me why.

https://github.com/ForestryMC/ForestryMC/issues/2005
https://github.com/superckl/BiomeTweaker/issues/174

If this will not work, I will change the receipt. I think combination of silky propolis and royal jelly would be nice combination.

**Comment by gdarai** [comment]
Apro po, gendustry in't Very Late... :o) It is just that this pack is ment to be kind of long.... I believe that mutatron is in 15% of the way.

**Comment by gdarai** [comment]
Fixed in 0.65 for now by adding Hellish to Mesa and Desert Hills
