### ISSUE TITLE
Making Electron Tubes Obsolete

### ISSUE THREAD

**Issue by gdarai** [gdarai/SpaceRace#20]
One big topic is to make electron tubes obsolete (mostly) once the unified electronics (Transistors and microchips) are out.

Right now, there are some dual recipes where player can pick if to use Transistors or Tubes. But what next?

**Comment by gdarai** [comment]
Possible step might be some backwards compatibility. Ability to create at least the most basic Electron Tubes (copper, tin, iron, bronze) from tranzistor and something. Should it be thermionic, carpenter, crafting Crystalizer or Precision assembler receipt? I don't know yet. Or maybe I can create directly Crystalizer receipt for those tubes... from the nuggets, skipping transistors.

**Comment by gdarai** [comment]
Another topic is to be able to skip the Forestry Circuits... the big drain on eezo. Would that be good? Wanted?

**Comment by OlorinCZ** [comment]
I agree that since electron tubes are meant to be the primitive electronics which should be replaced by the unified versions, it makes no sense that you would need to return to the primitive process of making them or the circuit boards. Giving them some simplier recipe in one of the advanced machines seems fair.

**Comment by kotja3** [comment]
I would like crystalizer recipe.
