### ISSUE TITLE
Mo' Creatures + CMS

### ISSUE THREAD

**Issue by OlorinCZ** [gdarai/SpaceRace#21]
This proposed change is a BIG one and I'm well aware of it and it mostly stems from my unending hate of aquacreepers, but it is a thing I would very much like to see before the modpack leaves beta: The inclusion of Mo'Creatures.

Darai said he was considering adding it in the first place but he ran into some weird issues with the spawning. One of the thoughts of the modpack is to make water travel unsafe, thus forcing player into exploring Davinci ships. In the current build this is done by aquacreepers. Mo's has sharks which can do exactly the same and more: Sharks do not explode (!!!); do not jump out of the water; do not atack you while riding the ship and they will still eat your face when you try to swim amongst them. The mod seems very configurable and unwanted mobs can be just cut off.

To test the spawning and compatibility issues I downloaded Mo'creatures and it's prequisite Custom Mob Spawner from the official website and I started a new game. All of the spawns seemed normal; maybe a bit too frequent (which can be tweaked), but nothing out of place:
![2018-03-01_11 57 30](https://user-images.githubusercontent.com/35596097/36843528-80ddfcf8-1d4f-11e8-9cc3-38a4faf83bb3.png)

This scanned the modpack and created the appropriate config files in the config folder. Using the guide from mod's website I tweaked them a bit to test the functionality. I disabled a wide wariety of mobs, changed some spawning frequencies and, more importanly, pumped up the shark spawn rate to really disencourage swimming.
![2018-03-01_12 33 08](https://user-images.githubusercontent.com/35596097/36843763-354bae42-1d50-11e8-9bfa-68d2aa4f8904.png)

As far as I can tell the changes did exactly what I wanted to do. During my flightover in creative, I have not seen single one disabled creature and the sea was full of sharks, so everything seems to work just fine on my end.

To conclude this:
Pros:
- getting rid of aquacreepers while maintaining their primary function
- adding more wildlife variability
- environment based spawn control: ocean sharks, mountain goats, swamp crocodiles, space wyverns,...

Cons:
- big change meaning a lot of tweaking and changes
- possibilty of interfering with other mob changing mods
- high number of mobs can cause lagging (by default it increases vanilla limits, yet the numbers can be tweaked)

Possible issues:
CMS overwrites vanilla spawning and thus may interfere with other mob changing mods. However the config files seem to react to the mods installed and to allow spawning via CMS. So far I have only tested it in the overworld and it seems to be working without problems. Also roguelike dungeons use spawners instead of vanilla spawning methods so there is no interference. If there are other features of the modpack this can interfere with, I'm not familiar with them yet so I cannot test it further.

Please consider this.

**Comment by gdarai** [comment]
Actually the tweaking would not be that big... only mod which will interract with this is Mob Properties. Oh... and Biome Tweaker... I don't remember what will have precedns in mob spawning... we have to test it. (Mob Properties has issues of it's own... but is so unique mod that I learned to work with it rather than getting rid of it.) Consciering... :o) And did not forget. :o) Thanks for starting the issue, at least we can track the observed behavior here.

**Comment by OlorinCZ** [comment]
Well as I understand it CMS did overwrite other spawning methods. But from the config files it seems that it has taken account of the previously existing changes: for example creepers were set not to spawn in plains and some other biomes, just as it is, without needing to reproduce this existing tweak manually.

**Comment by gdarai** [comment]
Really? I have to check this... this means that I need to tweak the CMS, not the BiomeTweaker any more... I must verify this. Also I don't knowif that means that CMS will always allign itself to BT, or just when I delete it's setting. Also it means that I must get into how set the correct values in CMS, because in such case I wil not set Mo'creatures spawning in BT if it will get overridden. Hmm... good hypothesis, I will verify it in a test build.

As For now I know, Mo Creaures does not override the changes from Mob Properties which is good.

**Comment by gdarai** [comment]
And now I know why I hate CMS - It took me 3 days to write a generator which can create those crazy CMS configuration files... now it will take me another 3 days to figure out, why the game does not want to accept them. But once we are commited... I will try to finish the job.

**Comment by gdarai** [comment]
My ongoing effort to include this is bringing first fruits.
I can now generate the required configuration files... well almost

I hanve now following issues. If I will be able to fix most of them we can have a go. If not, it was wasted effort.
Issue 1: No monsters and creatures are spawning on the AdvRocketry Biomes
Issue 2: No Mo Creatures are spawning on mushroom island
Issue 3: No Monsters are spawning in the UnderEnd
Issue 4: Wrong spawning of Ghasts, they spawn on ground, not in the air

We will see... I will try to address those issues today.

**Comment by gdarai** [comment]
And here is the final blow: Mo'Creatures without CMS cannot spawn water creatures...
People were overcomming this by using another spawning mod, but that is not available any more.

So, this let us 3 options...

AquaCreepers with the current nice variable world

MoC with CMS but with no creatures nowhere in the space, but the overworld and tweaked biomes, like lavaworld possibly also with issues like no creatures in UnderEnd, or wrongly generated creatures on asteroids

MoC wihout CMS with all the nice animals, but wihout aqua mobs... well we did that because of the Shark... so?

Sorry, I tried for a week now... this is the result. If you will want to continue with this endeavour be my guest, but I am done with this topic for now.

A pro po, for your experiments, you may need to be able to access different worlds and dimensions:
1) Turn off Restricted Portals Mod
2) Find the proper DIMID's of individual planets in config/AdvancedRocketry/PlanetDefs.cfg file.

Best luck... and sorry.

**Comment by OlorinCZ** [comment]
Well, it's sad that the compatibilities are so complicated. And a shame that there is no other custom spawning option for 1.10... When I have more time I will definetly do some experiments concerning the issues mentioned above, but it does not seem promising, that's certain.

**Comment by gdarai** [comment]
Now that I am over Mo'Creatures I focused on other concerning question from the same bucket: "Are there really no other mods with evil water animals we can use?"

I tried a lot of googling... google sucks in this, I tried keyword search in the twitch modlist, like "mob" "creature" "pir" "shark" "water" "aqua" "aq"...
Well at the and I gave up, I filtered all mods adding SOME animal and walked through them one by one and I have ONE oter option: Animania: 
https://minecraft.curseforge.com/projects/animania

It looks it has the same level of compatibility as AquaCreepers, It adds only 4 creatures, Bear, Wolf, Rat and Pirhanna... so it is super easy to tweak and fit into the pack. It follows the sommon spawning rules as vanilla mobs and so far it is not in any conflict with the curret mods... what do you think?

**Comment by OlorinCZ** [comment]
Animalium seems worth a shot. Shame I did not manage to google it in the first place.
While it doesn't have the fluff of Mo's I'm all for it as long as the pirhannas are non-explosive :)

**Comment by gdarai** [comment]
You know... the compatibilities is the reason, why it took me 4 months to set up the starting packet of mods. And also the reason why I am so hesitant changing / adding whole mods now that we are in beta. But in this case I believe it was worth it.

**Comment by OlorinCZ** [comment]
Oh I can imagine. And thank you for trying!

**Comment by gdarai** [comment]
Ok... I am closing this issue now. If you will have some more to this topic, we can always reopen it later.
