### ISSUE TITLE
Due to reduced stack size I cannot buy monastic bee

### ISSUE THREAD

**Issue by kotja3** [gdarai/SpaceRace#24]
Monastic drone costs one princess and 54 emerald, but because emerald stacksize is 16 I cannot buy one. Please return emerald stacksize back to 64. Or reduce prices but it will be more difficult.

**Comment by gdarai** [comment]
It seems I will have to... is it the standard villager trade? I will look if I can somehow tweak those. Other option (not as straightforward) for monastic bees is to loot the ships around your world. I found like 10 monastic drones this way. But conscider it only as workaround, I will definitely device a solution how to do the trade.

**Comment by kotja3** [comment]
It is apiarist villager.
Big or small ships?
Post how to edit stacksize.cfg
I guess, deleting emerald would be enough.

**Comment by gdarai** [comment]
Yes, that should work... Stacksize.cfg, remove th line 'emerald'. Emerald is only in that big group which sets a lot of thos things to 16... so delete it and it should be default 64.

on all the ships, because it is standard rewardchest item. The same things in standard vanilla dungeons.

Thanks to this I actually found a mod which can tweak all the villager trades... and even adds some more funny villagers, I will try to add it for the future,test it a little and we will see.

You know, this does not have to b only thing with villagers, so it will be good to have some controll over it.

**Comment by gdarai** [comment]
Ok... I tried with no luck... so I took your advice and increased the stack size at the end.
