### ISSUE TITLE
Compacting drawers - custom compressions

### ISSUE THREAD

**Issue by OlorinCZ** [gdarai/SpaceRace#30]
https://github.com/jaquadro/StorageDrawers/wiki/MineTweaker-API#item-compaction

You said you did not had any luck with configuring compacting drawers for unsupported items. The manual above seems to have the solution. Maybe it would also allow you to remove the chiseled blocks from the equation so you can solve the issue of unwanted compacting of chiseled blocks into the source blocks?

On a related note - Electrum is also missing the downgrading recipies (block>ingot>nugget)

**Comment by gdarai** [comment]
Good to know, I will look at the electrum.
I believe I fixed the redstone and the constantan and bronze... please try it and confirm.

With the Chiseled blocks... I will read it and hopefully break it, but I am not sure. Thanks for the link. We will see. The thing is that to make the chiseled blocks "cheaper" I have to do many things. 1) Disable compact drawers, 2) Disable oreDictionary, disable smelting and grinding. Find all recipes where they are used and be sure only the default block is used in those recipes.

For some of those it is harder than for the others, because the calculation of allowed recipes is done before minetweaker removes the chiseled blocks from the oreDict group... so I have to search even more.

**Comment by OlorinCZ** [comment]
Confrimation: Bronze, Constantan and even Redstone work fine both with crafting grid and the compacting drawers.

As for the chiseled blocks - I only said it might be a solution; whether or not implement it is your call.

Also, as I understand it the problem is the oreDict link between the chiseled blocks and regular metal blocks. Why not just remove them from oreDict alltogether and cut the problem by the source? Afaik the chiseled blocks are not used during worldgen so they would be only made by player for the purpose of decoration and they will be used for decoration, not crafting. And even if such player would later change his mind, he clearly has the means to convert them back via chisel. So - is there really any reason to have the chiseled metal blocks in the oreDict?

**Comment by gdarai** [comment]
So I believe this is done...
