### ISSUE TITLE
BQ Market

### ISSUE THREAD

**Issue by OlorinCZ** [gdarai/SpaceRace#32]
After testing the market under ver 0.77 I'm unfortunately still running into some problems. All the shopping and chains work fine until I try to make the reset.

Am I the only one with the problems? I hope we can identify the issue and fix it.

Odd thing is that the bug behaves differently in some situations - maybe it is affected by gamemode (being better in survival and worse in creative, although it may only be my imagination). On the other hand it certainly behaves different if you have "cheat mode" ON (and therefore have access to BQ admin commands.)

Screenshots from my first attempt with admin rights ON:
Just after reset, but it did not reset completely. The blue quests can not be selected.
![2018-06-08_13 14 31](https://user-images.githubusercontent.com/35596097/41162330-d3aa3224-6b35-11e8-838e-7bc4d106227e.png)
Continuing from previous screen and completing the Entering the market Q lead to this:
![2018-06-08_13 00 26](https://user-images.githubusercontent.com/35596097/41162397-088cda64-6b36-11e8-8cd8-61ec708ecafc.png)
Out of curiosity I tried the Emergency reset. It did restore the missing quests in the market tab, but deleted other ones and all the previous progress in other tabs.
![2018-06-08_13 15 48](https://user-images.githubusercontent.com/35596097/41162611-af51d430-6b36-11e8-9866-cb8a558063ca.png)
The whole "Builder" line just went fishing or what.
![2018-06-08_13 16 10](https://user-images.githubusercontent.com/35596097/41162621-b675b2c2-6b36-11e8-95b3-afd3014c857e.png)
On the other hand, it also opens these two tabs.
![2018-06-08_13 16 24](https://user-images.githubusercontent.com/35596097/41162742-0854cd62-6b37-11e8-86ed-b9477a61312d.png)
![2018-06-08_13 16 29](https://user-images.githubusercontent.com/35596097/41162745-093abb7e-6b37-11e8-9c66-a1ddfb7aa1ff.png)

Second attempt after a full reset, but this time with admin rights OFF:
Almost good, but as you can see the one quest I completed did not reset (or is this intended? I hope not.) And, despite it being the "ordinary reset", you can see the unlocked tabs on the left and the Selling Builder line also disappeared, similarily to my previous try.
![2018-06-08_13 27 23](https://user-images.githubusercontent.com/35596097/41162791-2b391c70-6b37-11e8-8a7d-e107b72bc589.png)
At the point of the reset, I got some white and some red warning messages:
![2018-06-08_13 27 11](https://user-images.githubusercontent.com/35596097/41163080-fe045480-6b37-11e8-84be-5afedd2a8ecf.png)
This time the Emergency reset did nothing good, it did reset a few quests but in the end it resulted in many more of those red warnings... I hope this data will help.

**Comment by gdarai** [comment]
Main question, does it make problem also after reset of ALL quests?
``` /bq_admin reset all``` ?
Ok... it tells me one thing... before full release, I have to test it once more and thorroughly.
I still think the issue are the quest_ids. I though I put them into  order by make them hardcoded... but maybe I did it wrongly.
Interresting things are:
#1 When I compare the DefaultQuests.json file from the last two versions... do have the same quests same QID's? I will check it for the market and let you know.
#2 The more interresting, if I start FRESH new game with the last -1 version, and update, will it still be problem?
If #1 will show differences than my code is wrong.
If my code is ok but #2 still shows problems... then it is some issue that the IDs keeps some legacy I cannot influence using the DefaultQuests.json.... but it will also mean that my code works and the issue is only for older games before the hardcoding.

**Comment by gdarai** [comment]
Also, there IS difference between creative and normal... from what I know, in creative the quests are not working correctly, so the better way is to have creative off, just JEI set to cheat in items.

You can distinguish those two states easily, because in one of them the quests just don't finish up... all of them.

**Comment by OlorinCZ** [comment]
Yes, it was both after the reset all command and load default command. Also the bug seems to affect the client now so after it occurs and I try to "save and quit to the title," it freezes. That's new to me and it might not be directly related.

Fresh world, survival, 0.77, cheat mode and bqm admin ON:
Upon reset the Buying essentials tab did reset just fine, but Basic training got wiped out and the two advandced tabs opened just like before. Btw I should add that in some tabs it sometimes just replaces existing quest with a completed, but totally blank one. That's what opens the closed tabs.

Another fresh world, survival, 0.77, cheat mode and bqm admin OFF:
Well... practically the same. To add to the list of damage done, it wiped some (but not all) quests in the hoarding tab; it completely shut off the cheats tab and it did erase my previous progress in the first tab, though the quests here are just reset and not broken. Also, no red warnings this time. I suspect that this might also be true in the previous case, but I already deleted that world (not smart).

And there is another thing: Continuing from the previous point (cheat mode now on so I can skip killing zombies) with the buying tab succesfuly reset and other tabs broken. I'm completing the trading once more and trying the reset for a second time - and this time it breaks this tab as well, even with some red warnings.

Conclusion: There might not be a difference between cheat mode on and off. There might be some legacy issue mixing the results, but the bug perists even on a clean world.

**Comment by gdarai** [comment]
Hmm... I will investigate and let you know.

**Comment by gdarai** [comment]
@OlorinCZ So as I see it, the big issue is the reseting of markets. Once you do a lot of ```bq_admin reset ID``` it just breaks... I will change the setting, so every store will have it's own reset and thus I will avoid this huge multi reset... hopefully.

**Comment by gdarai** [comment]
The important thing is that it is NOT an issue with legacy or compatibility between versions.

**Comment by gdarai** [comment]
Ok, so in the release I believe this is fixed.
I changed the Market and Trade quests, they are now Repeatable (with timer)
I had to replace Victory Score with Victory Items... since Score was also totally broken.
And I had to remove RF quest, since that is no longer working functionality.

Otherwise everything should be up and working.
